OCM-2369 | fix: update check commit format workflow

diff --git a/.github/workflows/check-commit-format.yml b/.github/workflows/check-commit-format.yml
--- a/.github/workflows/check-commit-format.yml
+++ b/.github/workflows/check-commit-format.yml
@@ -3,27 +3,19 @@
 name: 'Validate Commit Messages'
 on:
   pull_request:
-    types:
-      - opened
-      - edited
-      - reopened
-      - synchronize
-  pull_request_target:
-    types:
-      - opened
-      - edited
-      - reopened
-      - synchronize
+    branches:
+      - main
 
 jobs:
   parse-commit-messages:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
           fetch-depth: 0
           ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
       - name: Validate Commit Message(s)
         run: |
           IFS=$'\n' commit_messages=($(git log --pretty=format:"%s" HEAD...${{ github.event.pull_request.base.sha }}))          
@@ -31,8 +23,8 @@ jobs:
           for message in "${commit_messages[@]}"
           do
           echo "validating $message"
-          if ! echo "$message" | grep -qE "^[A-Z]+-[0-9]+ \| (feat|fix|docs|style|refactor|test|chore|build|ci|perf) : .*$"; then
-            echo "Invalid commit message format. Expected format: JIRA_TICKET | TYPE : MESSAGE"
+          if ! echo "$message" | grep -qE "^[A-Z]+-[0-9]+ \| (feat|fix|docs|style|refactor|test|chore|build|ci|perf): .*$"; then
+            echo "Invalid commit message format. Expected format: JIRA_TICKET | TYPE: MESSAGE"
             exit 1
           fi
           done
